### ISSUE TITLE
[Installation][?Mac] "LocalSettings.php not found" error if script is run without mountPoint existing

### ISSUE THREAD

**Issue by Luan-vP** [FantasticoFox/micro-PKC#28]
Steps to reproduce:

./pkc setup is run without a mountPoint folder
-> localhost:9352 gives a "Missing LocalSettings.php" error
inside the container, there is no /var/www/html/LocalSettings.php, and also no /backups/LocalSettings.php

run docker-compose down
*do not delete mountPoint/*

run the install script again, this time localhost:9352 works as expected
/var/www/html and /backup now both contain LocalSettings.php

**Comment by Luan-vP** [comment]
^ Look into this being a symlink

**Comment by Luan-vP** [comment]
<img width="1107" alt="Screenshot 2021-09-30 at 15 34 32" src="https://user-images.githubusercontent.com/77932581/135482193-1f85178d-9bd3-4e52-8111-b2fb0f57ce66.png">

<img width="564" alt="Screenshot 2021-09-30 at 15 34 12" src="https://user-images.githubusercontent.com/77932581/135482231-d2fee978-1b36-4659-9b5d-1f2bf224cd77.png">

**Comment by rht** [comment]
OK we manage to isolate the issue to be DB connection refused. Which means that install.php (for setting up MediaWiki) fails because the MySQL db isn't ready yet. A quickfix would be to sleep longer than the currently hardcoded 15s. But ideally we should just implement a way to retry installation if it fails because of DB connection problem.

And so, the proper issue is actually #29.
